### ISSUE TITLE
추가 애드온 등록 건의

### ISSUE THREAD

**Issue by n-andflash** [HAKorea/addons#4]
안녕하세요, 저장장치입니다.

삼성SDS 월패드 애드온을 새로 만든게 있는데, MQTT discovery랑 조명 패킷 관련 자동파악하는 코드 등을 추가해서
처음 설정하시는 분들이 코드나 yaml 직접 손댈 필요 없이 기존 애드온보다 좀 편하게 하실수 있을거 같은데
이 애드온도 HAKorea 저장소에 등록이 가능할까요?
nodejs가 아니라 python으로 짜서 기존 월패드 애드온에 js만 추가하는 형태로는 안될거 같아요.

주소는 https://github.com/n-andflash/ha_addons/tree/master/sds_wallpad 입니다.

**Comment by zooil** [comment]
애드온은 각자의 저장소에서 만들어 두면 그것을 이곳의  subtree로 관리중입니다.
추가해보겠습니다.

**Comment by zooil** [comment]
애드온에 추가했습니다. 이슈는 마감할게요!
